#Based on template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-CMake.yml
name: Build

env:
  GH_TOKEN: "${{github.token}}"
  Branch: "${{github.ref_name}}"
  Artifacts: "build/Win64_Unified"
  Extension: "*"
  Title: "${{github.event.repository.name}}"
  CUDA_VERSION_MAJOR: "12"
  CUDA_VERSION_MINOR: "9"
  CUDA_VERSION_PATCH: "1"
  CUDA_DRIVER_VERSION: "576.57"
  TENSORRT_VERSION_MAJOR: "10"
  TENSORRT_VERSION_MINOR: "16"
  TENSORRT_VERSION_PATCH: "0"
  TENSORRT_VERSION_BUILD: "72"
  TENSORRT_RTX_VERSION_MAJOR: "1"
  TENSORRT_RTX_VERSION_MINOR: "4"
  TENSORRT_RTX_VERSION_PATCH: "0"
  TENSORRT_RTX_VERSION_BUILD: "76"

on:
  push:
    Branches: "$Branch"
  pull_request:
    Branches: "$Branch"
  workflow_dispatch:

jobs:
  Build:
    name: ${{matrix.Settings.Name}}-${{matrix.Configuration}}
    runs-on: windows-2022
    strategy:
      matrix:
        Configuration: [Release]
        Settings:
        - {
            Name: "Win64",
            Platform: "x64",
            Architecture: "x64",
            Triplet: "x64-windows"
          }

    steps:

    - name: Clone repo and submodules
      run: >
        git
        clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git
        "${{github.workspace}}"
        --branch ${{env.Branch}}
        --recurse-submodules
        --depth 1

    - name: Cache vcpkg
      uses: actions/cache@v5
      id: cache_vcpkg
      with:
        path: C:/vcpkg/installed
        key: vcpkg
    - name: vcpkg
      if: steps.cache_vcpkg.outputs.cache-hit != 'true'
      run: |
        vcpkg install --triplet ${{matrix.Settings.Triplet}}
    - name: List vcpkg files
      run: Get-ChildItem -Path "C:\vcpkg" -File -Recurse | Select-Object FullName

    - name: Get Visual Studio path
      run: |
        vswhere.exe -property installationPath
        echo "VS_PATH=$(vswhere.exe -property installationPath)" >> $env:GITHUB_ENV
    - name: Cache CUDA
      id: cache-cuda
      uses: actions/cache@v5
      with:
        path: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}"
        key: CUDA_V${{env.CUDA_VERSION_MAJOR}}_${{env.CUDA_VERSION_MINOR}}
    - name: Download CUDA
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      run: |
        curl --ssl-revoke-best-effort --fail -L "https://developer.download.nvidia.com/compute/cuda/${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.${{env.CUDA_VERSION_PATCH}}/local_installers/cuda_${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.${{env.CUDA_VERSION_PATCH}}_${{env.CUDA_DRIVER_VERSION}}_windows.exe" -o "CUDA.exe" || true
        curl --ssl-revoke-best-effort --fail -L "https://developer.download.nvidia.com/compute/cuda/${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.${{env.CUDA_VERSION_PATCH}}/local_installers/cuda_${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.${{env.CUDA_VERSION_PATCH}}_windows.exe" -o "CUDA.exe" || true
    - name: Install CUDA
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      run: |
        Start-Process -Wait "CUDA.exe" -ArgumentList "-s"
    - name: Set CUDA path
      run: |
        echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}" >> $env:GITHUB_ENV
        echo "CUDA_PATH_V${{env.CUDA_VERSION_MAJOR}}_${{env.CUDA_VERSION_MINOR}}=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}" >> $env:GITHUB_ENV
        echo "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}" >> $env:GITHUB_ENV
        echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9\include" >> "$GITHUB_PATH"
#          echo "PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\bin\x64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\include;$Env:Path" >> $env:GITHUB_ENV
    - name: List files
      run: Get-ChildItem -Path "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\include" -File -Recurse | Select-Object FullName
    - name: CUDA Visual Studio integration
      if: steps.cache-cuda.outputs.cache-hit != 'false'
      run: |
        copy "${{env.CUDA_PATH}}\extras\visual_studio_integration\MSBuildExtensions\*" "${{env.VS_PATH}}\MSBuild\Microsoft\VC\v160\BuildCustomizations"
        copy "${{env.CUDA_PATH}}\extras\visual_studio_integration\MSBuildExtensions\*" "${{env.VS_PATH}}\MSBuild\Microsoft\VC\v170\BuildCustomizations"
    - name: List CUDA Visual Studio integration files
      run: |
        ls -R "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\extras\visual_studio_integration\MSBuildExtensions"
        ls -R "${{env.VS_PATH}}\MSBuild\Microsoft\VC\v160\BuildCustomizations"
        ls -R "${{env.VS_PATH}}\MSBuild\Microsoft\VC\v170\BuildCustomizations"

    - name: Download TensorRT
      run: |
        curl --ssl-revoke-best-effort --create-dirs -L "https://developer.download.nvidia.com/compute/machine-learning/tensorrt/${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}/zip/TensorRT-${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}.${{env.TENSORRT_VERSION_BUILD}}.Windows.amd64.cuda-${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.zip" -o "TensorRT.zip" || true
        7z x "TensorRT.zip"
    - name: Download TensorRT RTX
      run: |
        curl --ssl-revoke-best-effort --fail --create-dirs -L "https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}/TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}.Windows.win10.cuda-${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}.zip" -o "TensorRT-RTX.zip" || true
        curl --ssl-revoke-best-effort --fail --create-dirs -L "https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}/TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}-Windows-amd64-cuda-${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}-Release-external.zip" -o "TensorRT-RTX.zip" || true
        7z x "TensorRT-RTX.zip"
        ROBOCOPY /MOVE /S "TensorRT-${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}.${{env.TENSORRT_VERSION_BUILD}}" "TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}" || true

    - name: Download onnxruntime
      run: |
        curl --ssl-revoke-best-effort --create-dirs -L "https://github.com/ThreeDeeJay/onnxruntime/releases/download/TensorRT-RTX-75/onnxruntime.zip" -o "onnxruntime.zip"
        git clone https://github.com/ThreeDeeJay/onnxruntime --branch multi-ep --depth 1
        7z x "onnxruntime.zip"
        move "Win64" "onnxruntime\lib"

    - name: Configure
      run: >
        cmake
        -A "${{matrix.Settings.Platform}}"
        -B "${{github.workspace}}/build"
        -DCMAKE_BUILD_TYPE=${{matrix.Configuration}}
        -DCMAKE_PREFIX_PATH=C:\vcpkg\installed\${{matrix.Settings.Triplet}}
        -DORT_BACKEND=Unified
        -DORT_UNIFIED_DIR="${{github.workspace}}\onnxruntime"
        -DORT_TRTRTX_HOME="${{github.workspace}}\TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}"
#        -DORT_TRTRTX_HOME="${{github.workspace}}\TensorRT-${{env.TENSORRT_VERSION_MAJOR}}.${{env.TENSORRT_VERSION_MINOR}}.${{env.TENSORRT_VERSION_PATCH}}.${{env.TENSORRT_VERSION_BUILD}}"

    - name: Build
      run: >
        cmake
        --build "${{github.workspace}}/build"
        --config "${{matrix.Configuration}}"

    - name: List files
      run: Get-ChildItem -Path "." -File -Recurse | Select-Object FullName

    - name: Deploy
      shell: cmd
      run: |
        move /Y "3Deflatten.ini"                                                                                                                                                                                                                                                        "${{env.Artifacts}}/"
        move /Y "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\bin\cudart64_${{env.CUDA_VERSION_MAJOR}}.dll"                                                                                                              "${{env.Artifacts}}/"
        move /Y "TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}\bin\nvinfer_${{env.TENSORRT_VERSION_MAJOR}}.dll"                                                          "${{env.Artifacts}}/"
        move /Y "TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}\bin\nvonnxparser_${{env.TENSORRT_VERSION_MAJOR}}.dll"                                                     "${{env.Artifacts}}/"
        move /Y "onnxruntime\lib\onnxruntime.dll"                                                                                                                                                                                                                                       "${{env.Artifacts}}/"
        move /Y "onnxruntime\lib\onnxruntime_providers_shared.dll"                                                                                                                                                                                                                      "${{env.Artifacts}}/"
        move /Y "onnxruntime\lib\DirectML.dll"                                                                                                                                                                                                                                          "${{env.Artifacts}}/"
#        move /Y "onnxruntime\lib\onnxruntime_providers_cuda.dll"                                                                                                                                                                                                                       "${{env.Artifacts}}/"
#        move /Y "onnxruntime\lib\onnxruntime_providers_tensorrt.dll"                                                                                                                                                                                                                   "${{env.Artifacts}}/"
#        move /Y "onnxruntime\lib\onnxruntime_providers_nv_tensorrt_rtx.dll"                                                                                                                                                                                                            "${{env.Artifacts}}/"
#        move /Y "TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}\bin\tensorrt_rtx_${{env.TENSORRT_RTX_VERSION_MAJOR}}_${{env.TENSORRT_RTX_VERSION_MINOR}}.dll"            "${{env.Artifacts}}/"
#        move /Y "TensorRT-RTX-${{env.TENSORRT_RTX_VERSION_MAJOR}}.${{env.TENSORRT_RTX_VERSION_MINOR}}.${{env.TENSORRT_RTX_VERSION_PATCH}}.${{env.TENSORRT_RTX_VERSION_BUILD}}\bin\tensorrt_onnxparser_rtx_${{env.TENSORRT_RTX_VERSION_MAJOR}}_${{env.TENSORRT_RTX_VERSION_MINOR}}.dll" "${{env.Artifacts}}/"
#        move /Y "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${{env.CUDA_VERSION_MAJOR}}.${{env.CUDA_VERSION_MINOR}}\bin\*.dll"                                                                                                                                                "${{env.Artifacts}}/"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.Title}}-${{matrix.Settings.Name}}-${{matrix.Configuration}}
        path: "${{github.workspace}}/${{env.Artifacts}}/${{env.Extension}}"

  Release:
    name: Release
    if: github.event_name == 'push'
    runs-on: windows-latest
    needs: Build
    steps:

      - name: Clone repo and submodules
        run: git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git "${{github.workspace}}" --branch ${{env.Branch}} --recurse-submodules

      - name: Get current date, commit hash and count
        run: |
          echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
          echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
          echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
          echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
          echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV

      - name: Download Artifacts - Win64
        uses: actions/download-artifact@v4
        with:
          name: ${{env.Title}}-Win64-Release
          path: Release/Win64/

      - name: Deploy
        run: |
          copy "3Deflatten.ini"                          "Release/Win64/"
          copy "README.md"                               "Release/ReadMe.txt"
          copy "LICENSE"                                 "Release/License.txt"
          copy "scripts/collect_runtime_dlls_cuda12.py"  "Release/Runtimes.py"
#          copy "scripts/Setup.py"                        "Release/"
#          copy "scripts/collect_runtime_dlls_cuda13.py"  "Release/"
#          copy "scripts/register.bat"                    "Release/"
#          copy "scripts/unregister.bat"                  "Release/"

      - name: Compress artifacts
        run: |
          7z a "Release/${{env.Title}}.zip" "${{github.workspace}}/Release/*" -mx=9
          cp "Release/${{env.Title}}.zip" "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

      - name: Purge tag - latest-${{env.Branch}}
        run: |
          gh release delete latest-${{env.Branch}} --repo ${{github.repository}} --cleanup-tag --yes || true

      - name: Release - latest-${{env.Branch}}
        run: |
          gh release create latest-${{env.Branch}} --repo ${{github.repository}} --target ${{env.CommitHash}} --generate-notes --latest=false --prerelease --title "${{env.Title}} r${{env.CommitCount}}@${{env.CommitHashShort}}" --notes "Build archive: https://github.com/${{github.repository}}/releases/tag/archive-${{env.Branch}}
          Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          gh release upload latest-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}.zip"

      - name: Release - archive-${{env.Branch}}
        run: |
          gh release create archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
          Build logs: https://github.com/${{github.repository}}/actions" || true
          gh release edit archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
          Build logs: https://github.com/${{github.repository}}/actions" || true
          gh release upload archive-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"